### PR TITLE
Pushback feature, 2017.2+ Splash System

### PR DESCRIPTION
**Pull request by RenanMsV**
Pushback feature : Using pushback system now helicopter can be moved to any position you like.
Pushback 3D model will be static for now until I animate them.
https://i.imgur.com/QiJ9R6I.png
https://i.imgur.com/OJP9Gzm.png

2017.2+ Splash system now compatible. ( I think it requires new splashs with no letters since the new system write aircraft authors, infos at runtime ).

### CODE REVIEW

**Comment by IAHM-COL** [comment]
Is this an helicopter? are you suppose to push back one ?

**Comment by RenanMsV** [comment]
Yes, since they do not have wheels. 

http://www.helicopterwheels.com/wp-content/uploads/2008/04/towbar5.jpg
http://www.helitowcart.com/images/accessories/towbars/helitowcart_towbar_r44_banner.jpg

They use this to store in hangars.
I think 'pushback' exactly is not the correct name for a helicopter ... but...

**Comment by FGDATA** [comment]
> I think 'pushback' exactly is not the correct name for a helicopter ... but...

OK. I get you now. Hilarious.

**Comment by RenanMsV** [comment]
New seats uv-map and texture

**Comment by legoboyvdlp** [comment]
Well, they "push" the helicopter back, so I think it is OK :)

**Pull request merged**
